baseURL = "https://example.org/"
locale = "en-us"
title = "Erfan Jaripour"
theme = "PaperMod"

[params]
customCSS = ["css/extended/custom.css"]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 20

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 30

  [[menu.main]]
    identifier = "journal"
    name = "Research Journal"
    url = "/journal/"
    weight = 40

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 50

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 60

