baseURL = "https://erfanjaripour.github.io/"
locale = "en-us"
title = "Erfan Jaripour"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  customCSS = ["css/extended/custom.css"]

  email = "erfanjaripour@gmail.com"
  github = "https://github.com/erfanjaripour"
  psyarxiv = "https://osf.io/j2ws4/"
  orcid = "https://orcid.org/0009-0009-3229-4721"

  author = "Erfan Jaripour"

  description = "Personal academic website of Erfan Jaripour. Research in computational cognitive science, Bayesian cognitive modeling, working memory, learning."
  
  keywords = [
    "Erfan Jaripour",
    "Computational Cognitive Science"
  ]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 20

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 30

  [[menu.main]]
    identifier = "notes"
    name = "Research Notes"
    url = "/notes/"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 60

